baseURL: https://xtopy.com/
languageCode: en-us
title: XtoPY 
theme: "PaperMod"
paginate: 3
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true
googleAnalytics: UA-123-45
googleAnalytics: G-MEASUREMENT_ID
minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: XtopY
    description: "A blog about Stats, Analytics, Automation with Python by Allwyn Fernandes"
    keywords: [Blog, Python, Statistics, Maths, Analytics]
    author: Allwyn
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowFullTextinRSS: true

    math: true

    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false


    assets:
        disableHLJS: false # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/static/favicon.ico"
        favicon16x16: "favicon-16x16.png"
        favicon32x32: "favicon-32x32.png"
        apple_touch_icon: "/static/favicon.png"
        safari_pinned_tab: "/static/favicon.png"

    label:
        text: "XtoPY"
        icon: "/static/favicon32.ico"
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        # title: ExampleSite
        # subtitle: "This is subtitle"
        # imageUrl: "<img location>"
        # imageWidth: 120
        # imageHeight: 120
        # imageTitle: my image
        # buttons:
        #     - name: Posts
        #       url: posts
        #     - name: Tags
        #       url: tags



    # home-info mode
    homeInfoParams:
        Title: "Hey there \U0001F44B"
        Content: "I'm an analyst studying mathematics at IIT Madras. This is my blog on Stats, Analytics and Automation with Python"



    socialIcons:
        - name: twitter
          url: "https://twitter.com/thisallwyn"
        - name: github
          url: "https://github.com/allwynfernandes"
        - name: rss
          url: "/index.xml"


    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page
        responsiveImages: false

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]


menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: ideas
          url: /tags/
          weight: 20
        - identifier: archives
          name: archives
          url: /archives/
          weight: 30        # - identifier: resume
        - identifier: search
          name: search
          url: /search/
          weight: 40
                  #   name: Resume
        #   url: <link to resume>
        #   weight: 30


pygmentsUseClasses: true
markup:
    highlight:
        anchorLineNos: false
        codeFences: true
        guessSyntax: true
        lineNos: false
        noClasses: false
        style: monokai


outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary